// MOVIES ACTIONS

export const GET_MOVIES_REQUESTED = 'GET_MOVIES_REQUESTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILED = 'GET_MOVIES_FAILED';

export const GET_POPULAR_MOVIES_REQUESTED = 'GET_POPULAR_MOVIES_REQUESTED';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILED = 'GET_POPULAR_MOVIES_FAILED';

export const GET_NOW_PLAYING_MOVIES_REQUESTED = 'GET_NOW_PLAYING_MOVIES_REQUESTED';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';
export const GET_NOW_PLAYING_MOVIES_FAILED = 'GET_NOW_PLAYING_MOVIES_FAILED';

export const GET_UPCOMING_MOVIES_REQUESTED = 'GET_UPCOMING_MOVIES_REQUESTED';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_FAILED = 'GET_UPCOMING_MOVIES_FAILED';

export const GET_TOP_RATED_MOVIES_REQUESTED = 'GET_TOP_RATED_MOVIES_REQUESTED';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_FAILED = 'GET_TOP_RATED_MOVIES_FAILED';


// TV SHOWS ACTIONS

export const GET_POPULAR_TV_SHOWS_REQUESTED = 'GET_POPULAR_TV_SHOWS_REQUESTED';
export const GET_POPULAR_TV_SHOWS_SUCCESS = 'GET_POPULAR_TV_SHOWS_SUCCESS';
export const GET_POPULAR_TV_SHOWS_FAILED = 'GET_POPULAR_TV_SHOWS_FAILED';

export const GET_AIRING_TODAY_TV_SHOWS_REQUESTED = 'GET_AIRING_TODAY_TV_SHOWS_REQUESTED';
export const GET_AIRING_TODAY_TV_SHOWS_SUCCESS = 'GET_AIRING_TODAY_TV_SHOWS_SUCCESS';
export const GET_AIRING_TODAY_TV_SHOWS_FAILED = 'GET_AIRING_TODAY_TV_SHOWS_FAILED';

export const GET_ON_AIR_TV_SHOWS_REQUESTED = 'GET_ON_AIR_TV_SHOWS_REQUESTED';
export const GET_ON_AIR_TV_SHOWS_SUCCESS = 'GET_ON_AIR_TV_SHOWS_SUCCESS';
export const GET_ON_AIR_TV_SHOWS_FAILED = 'GET_ON_AIR_TV_SHOWS_FAILED';

export const GET_TOP_RATED_TV_SHOWS_REQUESTED = 'GET_TOP_RATED_TV_SHOWS_REQUESTED';
export const GET_TOP_RATED_TV_SHOWS_SUCCESS = 'GET_TOP_RATED_TV_SHOWS_SUCCESS';
export const GET_TOP_RATED_TV_SHOWS_FAILED = 'GET_TOP_RATED_TV_SHOWS_FAILED';