// MOVIES ACTIONS

export const GET_MOVIES_REQUESTED = 'GET_MOVIES_REQUESTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILED = 'GET_MOVIES_FAILED';

export const GET_POPULAR_MOVIES_REQUESTED = 'GET_POPULAR_MOVIES_REQUESTED';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILED = 'GET_POPULAR_MOVIES_FAILED';

export const GET_NOW_PLAYING_MOVIES_REQUESTED = 'GET_NOW_PLAYING_MOVIES_REQUESTED';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';
export const GET_NOW_PLAYING_MOVIES_FAILED = 'GET_NOW_PLAYING_MOVIES_FAILED';

export const GET_UPCOMING_MOVIES_REQUESTED = 'GET_UPCOMING_MOVIES_REQUESTED';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_FAILED = 'GET_UPCOMING_MOVIES_FAILED';

export const GET_TOP_RATED_MOVIES_REQUESTED = 'GET_TOP_RATED_MOVIES_REQUESTED';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_FAILED = 'GET_TOP_RATED_MOVIES_FAILED';

export const GET_MOVIE_DETAILS_REQUESTED = 'GET_MOVIE_DETAILS_REQUESTED';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILED = 'GET_MOVIE_DETAILS_FAILED';

export const GET_MOVIE_CREDITS_REQUESTED = 'GET_MOVIE_CREDITS_REQUESTED';
export const GET_MOVIE_CREDITS_SUCCESS = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIE_CREDITS_FAILED = 'GET_MOVIE_CREDITS_FAILED';

export const GET_MOVIE_KEYWORDS_REQUESTED = 'GET_MOVIE_KEYWORDS_REQUESTED';
export const GET_MOVIE_KEYWORDS_SUCCESS = 'GET_MOVIE_KEYWORDS_SUCCESS';
export const GET_MOVIE_KEYWORDS_FAILED = 'GET_MOVIE_KEYWORDS_FAILED';

export const GET_MOVIE_REVIEWS_REQUESTED = 'GET_MOVIE_REVIEWS_REQUESTED';
export const GET_MOVIE_REVIEWS_SUCCESS = 'GET_MOVIE_REVIEWS_SUCCESS';
export const GET_MOVIE_REVIEWS_FAILED = 'GET_MOVIE_REVIEWS_FAILED';

export const GET_MOVIE_RECOMMENDATIONS_REQUESTED = 'GET_MOVIE_RECOMMENDATIONS_REQUESTED';
export const GET_MOVIE_RECOMMENDATIONS_SUCCESS = 'GET_MOVIE_RECOMMENDATIONS_SUCCESS';
export const GET_MOVIE_RECOMMENDATIONS_FAILED = 'GET_MOVIE_RECOMMENDATIONS_FAILED';

export const GET_MOVIE_MEDIA_VIDEOS_REQUESTED = 'GET_MOVIE_MEDIA_VIDEOS_REQUESTED';
export const GET_MOVIE_MEDIA_VIDEOS_SUCCESS = 'GET_MOVIE_MEDIA_VIDEOS_SUCCESS';
export const GET_MOVIE_MEDIA_VIDEOS_FAILED = 'GET_MOVIE_MEDIA_VIDEOS_FAILED';


// TV SHOWS ACTIONS

export const GET_POPULAR_TV_SHOWS_REQUESTED = 'GET_POPULAR_TV_SHOWS_REQUESTED';
export const GET_POPULAR_TV_SHOWS_SUCCESS = 'GET_POPULAR_TV_SHOWS_SUCCESS';
export const GET_POPULAR_TV_SHOWS_FAILED = 'GET_POPULAR_TV_SHOWS_FAILED';

export const GET_AIRING_TODAY_TV_SHOWS_REQUESTED = 'GET_AIRING_TODAY_TV_SHOWS_REQUESTED';
export const GET_AIRING_TODAY_TV_SHOWS_SUCCESS = 'GET_AIRING_TODAY_TV_SHOWS_SUCCESS';
export const GET_AIRING_TODAY_TV_SHOWS_FAILED = 'GET_AIRING_TODAY_TV_SHOWS_FAILED';

export const GET_ON_AIR_TV_SHOWS_REQUESTED = 'GET_ON_AIR_TV_SHOWS_REQUESTED';
export const GET_ON_AIR_TV_SHOWS_SUCCESS = 'GET_ON_AIR_TV_SHOWS_SUCCESS';
export const GET_ON_AIR_TV_SHOWS_FAILED = 'GET_ON_AIR_TV_SHOWS_FAILED';

export const GET_TOP_RATED_TV_SHOWS_REQUESTED = 'GET_TOP_RATED_TV_SHOWS_REQUESTED';
export const GET_TOP_RATED_TV_SHOWS_SUCCESS = 'GET_TOP_RATED_TV_SHOWS_SUCCESS';
export const GET_TOP_RATED_TV_SHOWS_FAILED = 'GET_TOP_RATED_TV_SHOWS_FAILED';

export const GET_TV_SHOWS_DETAILS_REQUESTED = 'GET_TV_SHOWS_DETAILS_REQUESTED';
export const GET_TV_SHOWS_DETAILS_SUCCESS = 'GET_TV_SHOWS_DETAILS_SUCCESS';
export const GET_TV_SHOWS_DETAILS_FAILED = 'GET_TV_SHOWS_DETAILS_FAILED';

export const GET_TV_SHOWS_CREDITS_REQUESTED = 'GET_TV_SHOWS_CREDITS_REQUESTED';
export const GET_TV_SHOWS_CREDITS_SUCCESS = 'GET_TV_SHOWS_CREDITS_SUCCESS';
export const GET_TV_SHOWS_CREDITS_FAILED = 'GET_TV_SHOWS_CREDITS_FAILED';

export const GET_TV_SHOWS_KEYWORDS_REQUESTED = 'GET_TV_SHOWS_KEYWORDS_REQUESTED';
export const GET_TV_SHOWS_KEYWORDS_SUCCESS = 'GET_TV_SHOWS_KEYWORDS_SUCCESS';
export const GET_TV_SHOWS_KEYWORDS_FAILED = 'GET_TV_SHOWS_KEYWORDS_FAILED';

export const GET_TV_SHOWS_SEASON_DETAILS_REQUESTED = 'GET_TV_SHOWS_SEASON_DETAILS_REQUESTED';
export const GET_TV_SHOWS_SEASON_DETAILS_SUCCESS = 'GET_TV_SHOWS_SEASON_DETAILS_SUCCESS';
export const GET_TV_SHOWS_SEASON_DETAILS_FAILED = 'GET_TV_SHOWS_SEASON_DETAILS_FAILED';

// SEARCH ACTIONS

export const GET_SEARCH_MOVIES_REQUESTED = 'GET_SEARCH_MOVIES_REQUESTED';
export const GET_SEARCH_MOVIES_SUCCESS = 'GET_SEARCH_MOVIES_SUCCESS';
export const GET_SEARCH_MOVIES_FAILED = 'GET_SEARCH_MOVIES_FAILED';

export const GET_SEARCH_TV_SHOWS_REQUESTED = 'GET_SEARCH_TV_SHOWS_REQUESTED';
export const GET_SEARCH_TV_SHOWS_SUCCESS = 'GET_SEARCH_TV_SHOWS_SUCCESS';
export const GET_SEARCH_TV_SHOWS_FAILED = 'GET_SEARCH_TV_SHOWS_FAILED';

export const GET_SEARCH_PEOPLE_REQUESTED = 'GET_SEARCH_PEOPLE_REQUESTED';
export const GET_SEARCH_PEOPLE_SUCCESS = 'GET_SEARCH_PEOPLE_SUCCESS';
export const GET_SEARCH_PEOPLE_FAILED = 'GET_SEARCH_PEOPLE_FAILED';

export const GET_SEARCH_COLLECTION_REQUESTED = 'GET_SEARCH_COLLECTION_REQUESTED';
export const GET_SEARCH_COLLECTION_SUCCESS = 'GET_SEARCH_COLLECTION_SUCCESS';
export const GET_SEARCH_COLLECTION_FAILED = 'GET_SEARCH_COLLECTION_FAILED';

export const GET_SEARCH_COMPANIES_REQUESTED = 'GET_SEARCH_COMPANIES_REQUESTED';
export const GET_SEARCH_COMPANIES_SUCCESS = 'GET_SEARCH_COMPANIES_SUCCESS';
export const GET_SEARCH_COMPANIES_FAILED = 'GET_SEARCH_COMPANIES_FAILED';

export const GET_SEARCH_KEYWORDS_REQUESTED = 'GET_SEARCH_KEYWORDS_REQUESTED';
export const GET_SEARCH_KEYWORDS_SUCCESS = 'GET_SEARCH_KEYWORDS_SUCCESS';
export const GET_SEARCH_KEYWORDS_FAILED = 'GET_SEARCH_KEYWORDS_FAILED';