export const GET_MOVIES_REQUESTED = 'GET_MOVIES_REQUESTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILED = 'GET_MOVIES_FAILED';

export const GET_POPULAR_MOVIES_REQUESTED = 'GET_POPULAR_MOVIES_REQUESTED';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILED = 'GET_POPULAR_MOVIES_FAILED';

export const REMOVE_A_USER = 'REMOVE_A_USER';
